name: WorldPlus
main: com.plus.WorldPlus.Main
version: "1.5"
api: ["1.0.0"]

load: POSTWORLD

author: plus
description: 创世神插件for nukkit
commands:
 pos1:
  description: "设定位置1"
  usage: "/pos1"
 pos2:
  description: "设定位置2"
  usage: "/pos2"
 set:
  description: "设定方块"
  usage: "/set [方块ID] [zxc(主线程)/dxc(多线程)]"
 cut:
  description: "剪下方块"
  usage: "/cut [zxc(主线程)/dxc(多线程)]"
 copy:
  description: "复制方块"
  usage: "/cut [zxc(主线程)/dxc(多线程)]"
 paste:
  description: "贴上方块"
  usage: "/paste [zxc(主线程)/dxc(多线程)] [0(不旋转)/90[旋转90度]/180/270]"